//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_Cliente.srEditorial2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srEditorial2.wsEditorialSoap")]
    public interface wsEditorialSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string IdEditorial, string NombreEditorial, string Ciudad, string Estado, string Pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string IdEditorial, string NombreEditorial, string Ciudad, string Estado, string Pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string IdEditorial, string NombreEditorial, string Ciudad, string Estado, string Pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string IdEditorial, string NombreEditorial, string Ciudad, string Estado, string Pais);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsEditorialSoapChannel : ws_Cliente.srEditorial2.wsEditorialSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsEditorialSoapClient : System.ServiceModel.ClientBase<ws_Cliente.srEditorial2.wsEditorialSoap>, ws_Cliente.srEditorial2.wsEditorialSoap {
        
        public wsEditorialSoapClient() {
        }
        
        public wsEditorialSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsEditorialSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEditorialSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEditorialSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
        
        public string[] Agregar(string IdEditorial, string NombreEditorial, string Ciudad, string Estado, string Pais) {
            return base.Channel.Agregar(IdEditorial, NombreEditorial, Ciudad, Estado, Pais);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string IdEditorial, string NombreEditorial, string Ciudad, string Estado, string Pais) {
            return base.Channel.AgregarAsync(IdEditorial, NombreEditorial, Ciudad, Estado, Pais);
        }
        
        public string[] Actualizar(string IdEditorial, string NombreEditorial, string Ciudad, string Estado, string Pais) {
            return base.Channel.Actualizar(IdEditorial, NombreEditorial, Ciudad, Estado, Pais);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string IdEditorial, string NombreEditorial, string Ciudad, string Estado, string Pais) {
            return base.Channel.ActualizarAsync(IdEditorial, NombreEditorial, Ciudad, Estado, Pais);
        }
    }
}
