//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_Cliente.srTitulo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srTitulo.wsTituloSoap")]
    public interface wsTituloSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string IdLibro, string Titulo, string Tipo, string IdEditorial, string Precio, string Advance, string Royalty, string Ytdsales, string Notas, string Fechadepublicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string IdLibro, string Titulo, string Tipo, string IdEditorial, string Precio, string Advance, string Royalty, string Ytdsales, string Notas, string Fechadepublicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string IdLibro, string Titulo, string Tipo, string IdEditorial, string Precio, string Advance, string Royalty, string Ytdsales, string Notas, string Fechadepublicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string IdLibro, string Titulo, string Tipo, string IdEditorial, string Precio, string Advance, string Royalty, string Ytdsales, string Notas, string Fechadepublicacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsTituloSoapChannel : ws_Cliente.srTitulo.wsTituloSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsTituloSoapClient : System.ServiceModel.ClientBase<ws_Cliente.srTitulo.wsTituloSoap>, ws_Cliente.srTitulo.wsTituloSoap {
        
        public wsTituloSoapClient() {
        }
        
        public wsTituloSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsTituloSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTituloSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTituloSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string IdLibro, string Titulo, string Tipo, string IdEditorial, string Precio, string Advance, string Royalty, string Ytdsales, string Notas, string Fechadepublicacion) {
            return base.Channel.Agregar(IdLibro, Titulo, Tipo, IdEditorial, Precio, Advance, Royalty, Ytdsales, Notas, Fechadepublicacion);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string IdLibro, string Titulo, string Tipo, string IdEditorial, string Precio, string Advance, string Royalty, string Ytdsales, string Notas, string Fechadepublicacion) {
            return base.Channel.AgregarAsync(IdLibro, Titulo, Tipo, IdEditorial, Precio, Advance, Royalty, Ytdsales, Notas, Fechadepublicacion);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
        
        public string[] Actualizar(string IdLibro, string Titulo, string Tipo, string IdEditorial, string Precio, string Advance, string Royalty, string Ytdsales, string Notas, string Fechadepublicacion) {
            return base.Channel.Actualizar(IdLibro, Titulo, Tipo, IdEditorial, Precio, Advance, Royalty, Ytdsales, Notas, Fechadepublicacion);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string IdLibro, string Titulo, string Tipo, string IdEditorial, string Precio, string Advance, string Royalty, string Ytdsales, string Notas, string Fechadepublicacion) {
            return base.Channel.ActualizarAsync(IdLibro, Titulo, Tipo, IdEditorial, Precio, Advance, Royalty, Ytdsales, Notas, Fechadepublicacion);
        }
    }
}
